namespace:
  name: prod
service:
  port: 7111
replicas: 5
resources:
  requests:
    memory: "128Mi"
    cpu: "350m"
  limits:
    requests:
    memory: "256Mi"
    cpu: "500m"
image:
  pullPolicy: Always