name: techtrends package to dockerhub
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: qemu
        uses: docker/setup-qemu-action@v1
      - name: docker
        uses: docker/setup-buildx-action@v1
      - name: dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: dockeruser8623/techtrends:latest, dockeruser8623/techtrends:1.0.0

